#!/bin/sh

specfile=`ls -1 | grep .spec | head -n 1`
name=`grep "Name:" $specfile | awk '{print $2}'`
version=`grep "Version:" $specfile | awk '{print $2}'`

pwd=`pwd`
mkdir -p rpm/SOURCES >/dev/null 2>&1

git archive --prefix ${name}-${version}/ HEAD | gzip > rpm/SOURCES/${name}-${version}.tar.gz

rpmbuild -ba $specfile --define "%_topdir $pwd/rpm"
